### ISSUE TITLE
not working with container started from docker-compose

### ISSUE THREAD

**Issue by ProfEibe** [hrektts/docker-nginx-proxy#2]
Hi,

I got your project easy working with an angular/nginx webapp and an spring-boot restservice.
Both got their own urls everything works fine.

Now I wanted to combine them in an docker-compose file. I used the same Dockerfiles and defined the environment-variables in the docker-compose.yaml like I did on docker run.

When I start them everything works like before and I even see the PROXY_SUBDIR variable set in the new started container.

But my nginx-proxy isn't recognizing them. In the logs I get the following error:
```
Error inspecting container: 4782b18658fc3f211dbb3163d6bb389958a734a9605ab40f057f44063a75b539: No such container: 4782b18658fc3f211dbb3163d6bb389958a734a9605ab40f057f44063a75b539
```
I don't know where it gets this container_id from (maybe a docker-compose wrapper?), but it does not find the web and the rest container.

**Comment by hrektts** [comment]
Hello,

Unfortunately, I cannot reproduce the situation and have no idea about the container ID.
Did you deploy the backend services under the sub directories, which were set as `PROXY_SUBDIR`?

Could you compare your `docker-compose` file with [the one in this repo](https://github.com/hrektts/docker-nginx-proxy/blob/b772c80ec3fca4f22610a7ba704071b3f806ed7d/docker-compose.yml)? The backend service used in the file can be build from [the `Dockerfile`](https://github.com/hrektts/docker-nginx-proxy/tree/a12c15516f602cf6aa7fc74e47f1066ee2a2c544/test/backend).

**Comment by ProfEibe** [comment]
Thank you for your fast answer.
I think my docker-compose and my dockerfiles do not look so bad, so I will start to describe from scratch.


I've got an angular project with the following Dockerfile:
```
# Stage 1
FROM node:14-alpine as build-step
RUN apk add --no-cache git
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build -- --prod --base-href="/myapp/"

# Stage 2
FROM nginx:1.19.4-alpine
COPY --from=build-step /app/dist/myapp /usr/share/nginx/html/myapp
```
and i'ts java springboot Restservice with the following Docker file.
```
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8080 8787
ENTRYPOINT ["java","-jar","/app.jar","--server.servlet.context-path=/rest/myrest"]
```
Starting them with the following commands everything works fine and they are recognized by the nginx-proxy which I started previously:
```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro hrektts/nginx-proxy

docker build -t pwa/myapp .
docker run --rm -e PROXY_SUBDIR=/myapp --name pwa-myapp pwa/myapp

docker build -t rest/myrest .
docker run --rm -e PROXY_SUBDIR=/rest/myrest -e VIRTUAL_PORT=8080 --name rest-myrest rest/myrest
```
following is the working log of the proxy:

```
2020/11/20 07:14:37 Received event start for container dd09b7f91a5e
2020/11/20 07:14:37 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
2020/11/20 07:14:37 Running '/usr/sbin/nginx -s reload'
2020/11/20 07:14:56 Received event start for container 8ff334c1a991
2020/11/20 07:14:56 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
2020/11/20 07:14:56 Running '/usr/sbin/nginx -s reload'
```

Now I wanted to combine both of my projects to the following docker-compose file. The proxy receives the event start for the container, but ignores it and does not update its default.conf:
```
version: "3.8"
services:
  web:
    build: ./myapp
    environment:
      - PROXY_SUBDIR=/myapp
    expose: 
      - "80"
  
  rest:
    build: ./myrest
    environment:
      - PROXY_SUBDIR=/rest/myrest
      - VIRTUAL_PORT=8080
    expose: 
      - "8080"
      - "8787"
```
but now I only get the following proxy log
```
2020/11/20 07:01:23 Received event start for container 642ab8bd24dc
2020/11/20 07:01:23 Received event start for container 76e42b8124b2
2020/11/20 07:01:23 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification '/usr/sbin/nginx -s reload'
2020/11/20 07:01:23 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification '/usr/sbin/nginx -s reload'
```

**Comment by hrektts** [comment]
How about using [`ports`](https://docs.docker.com/compose/compose-file/#ports) instead of `expose` in your `docker-compose` file?

**Comment by ProfEibe** [comment]
Using ports did not change anything.

But it brought me to a solution. It wasn't expose or the ports it was the docker network.
Starting my apps with docker-compose created an own bridge network for only these two applications.
The proxy which was started outside had no connections to them.

I removed the expose part (because it is done by the dockerfile) and added a `network_mode: bridge` field to each service in the yaml-file, which connects each container to the default network.
Now it seams like it is working!
